name: Docker Image CI

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: false

jobs:
  build:
    steps:
    - name: Send Log         
      run: |
        echo "Name: ${{ inputs.name }}"
        
