name: Docker Image CI

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true

runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v3
    - name: Send Log    
      shell: bash
      run: |
          echo "Name: ${{inputs.name}}"
          echo "action_state: ${{env.action_state}}"



