name: Docker Image CI

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: false

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Send Log         
      run: |
          echo "sdfdsfsdf"
