name: Docker Image CI

on:
  workflow_call:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Send Log         
      run: |
        echo "action_state: ${{ env.action_state }}"
